<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250413020307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resource_project_allocation DROP CONSTRAINT fk_26ad680989329d25');
        $this->addSql('ALTER TABLE resource_project_allocation DROP CONSTRAINT fk_26ad6809166d1f9c');
        $this->addSql('ALTER TABLE resource DROP CONSTRAINT fk_bc91f41660984f51');
        $this->addSql('DROP TABLE resource_project_allocation');
        $this->addSql('DROP TABLE resource');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resource_project_allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, occupation_rate DOUBLE PRECISION NOT NULL, resource_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_26ad6809166d1f9c ON resource_project_allocation (project_id)');
        $this->addSql('CREATE INDEX idx_26ad680989329d25 ON resource_project_allocation (resource_id)');
        $this->addSql('CREATE TABLE resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, pole VARCHAR(100) NOT NULL, skills JSON NOT NULL, occupation_rate DOUBLE PRECISION NOT NULL, availability_rate DOUBLE PRECISION NOT NULL, "position" VARCHAR(255) NOT NULL, project_manager_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_bc91f41660984f51 ON resource (project_manager_id)');
        $this->addSql('ALTER TABLE resource_project_allocation ADD CONSTRAINT fk_26ad680989329d25 FOREIGN KEY (resource_id) REFERENCES resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource_project_allocation ADD CONSTRAINT fk_26ad6809166d1f9c FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT fk_bc91f41660984f51 FOREIGN KEY (project_manager_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
